flows:
  - name: raw_vault_and_infomart_schema_creation
    type: inner_database_flux
    sql:
      - create_raw_vault_structure.sql
      - information_mart_schema_creation.sql
      - staging_area_create_schema_structure.sql
  - name: paymenttypes_to_rv
    type: file_to_rv
    rv_object: paymenttypes # f"raw{dv_object}file"
    file_regex: "^paymenttypes_(?P<origin>.+?)_(?P<date>.+?)_.+?[.](?P<ext>.+?)$"
  - name: ratecodeids_to_rv
    type: file_to_rv
    rv_object: ratecodeids # f"raw{dv_object}file"
    file_regex: "^ratecodeids_(?P<origin>.+?)_(?P<date>.+?)_.+?[.](?P<ext>.+?)$"
  - name: vendors_to_rv
    type: file_to_rv
    rv_object: vendors # f"raw{dv_object}file"
    file_regex: "^vendors_(?P<origin>.+?)_(?P<date>.+?)_.+?[.](?P<ext>.+?)$"
  - name: trips_to_rv
    type: file_to_rv
    rv_object: trips # f"raw{dv_object}file"
    file_regex: "^trips_(?P<origin>.+?)_(?P<date>.+?)_.+?[.](?P<ext>.+?)$"
  - name: zones_to_rv
    type: file_to_rv
    rv_object: zones # f"raw{dv_object}file"
    file_regex: "^zones_(?P<origin>.+?)_(?P<date>.+?)_.+?[.](?P<ext>.+?)$"
  - name: sa_to_rv
    type: inner_database_flux
    hashfunc: sha256
    origin: csv
    sql:
      - raw_vault_load_1_hubtrips.sql
      - raw_vault_load_2_sattrips.sql
      - raw_vault_load_3_update_sattrips.sql
      - raw_vault_load_4_hubzones.sql
      - raw_vault_load_5_satzones.sql
      - raw_vault_load_6_update_satzones.sql
      - raw_vault_load_7_hubratecodeids.sql
      - raw_vault_load_8_satratecodeids.sql
      - raw_vault_load_9_update_satratecodeids.sql
      - raw_vault_load_10_hubpaymenttypes.sql
      - raw_vault_load_11_satpaymenttypes.sql
      - raw_vault_load_12_update_satpaymenttypes.sql
      - raw_vault_load_13_hubvendors.sql
      - raw_vault_load_14_satvendors.sql
      - raw_vault_load_15_update_satvendors.sql
      - raw_vault_load_16_linktrips.sql
  - name: rv_to_bv
    type: inner_database_flux
    bv_drop_trigger: 0
    sql: 
      - business_vault_create_1_schema_structure.sql
      - business_vault_create_2_timedim.sql
      - business_vault_create_3_vendordim.sql
      - business_vault_create_4_payment_typedim.sql
      - business_vault_create_5_ratecodedim.sql
      - business_vault_create_6_boroughdim.sql
      - business_vault_create_7_service_zonedim.sql
      - business_vault_create_8_service_zone_borough_correspondance.sql
      - business_vault_create_9_zonedim.sql
      - business_vault_create_10_payment_naturedim.sql
      - business_vault_create_11_tripfacts.sql
      - business_vault_load_1_tripfacts.sql
      - business_vault_load_2_service_zonedim.sql
      - business_vault_load_3_boroughdim.sql
      - business_vault_load_4_zonedim.sql
      - business_vault_load_5_service_zone_borough_correspondance.sql
      - business_vault_load_6_ratecodedim.sql
      - business_vault_load_7_vendordim.sql
      - business_vault_load_8_payment_typedim.sql
  - name: bv_to_infomart
    type: inner_database_flux
    sql: 
      - information_mart_1st_query.sql
      - information_mart_2nd_query.sql